import React, { useEffect, useState } from 'react';
import { Alert, Box, Button, Dialog, DialogActions, DialogContent, DialogTitle, IconButton, Stack, TextField, Typography } from '@mui/material';
import { AddRounded, CloseRounded, DeleteRounded, EditRounded } from '@mui/icons-material';
import { interviewService } from '../../services/api';
import PageHeader from '../UI/PageHeader';
import RoundBuilder from '../UI/RoundBuilder';
import SectionCard from '../UI/SectionCard';

const blank = { companyName: '', role: '', packageDetails: '', interviewDate: '', interviewTime: '', totalRounds: '', rounds: [], notes: '' };
const packageNumber = value => Number(String(value ?? '').replace(/[^0-9.]/g, ''));
const formatPackage = value => { const amount = packageNumber(value); return amount ? `${amount} LPA` : 'Not specified'; };
const monthlyEstimate = value => { const amount = packageNumber(value); return amount ? `₹${Math.round((amount * 100000) / 12).toLocaleString('en-IN')}/month` : 'Not specified'; };
export default function Interviews({ onChanged }) {
  const [items, setItems] = useState([]), [chosen, setChosen] = useState(null), [form, setForm] = useState(blank), [edit, setEdit] = useState(false), [error, setError] = useState('');
  const load = async () => { try { const response = await interviewService.getAll(); setItems(response.data?.data ?? response.data ?? []); } catch { setError('Could not load interviews.'); } };
  useEffect(() => { void load(); }, []);
  const open = item => { setChosen(item); setForm({ ...blank, ...item, rounds: item.rounds || [] }); setEdit(false); };
  const close = () => { setChosen(null); setEdit(false); };
  const save = async () => { try { const response = chosen ? await interviewService.update(chosen.id, form) : await interviewService.create(form); const item = response.data?.data ?? response.data; await load(); setChosen(item); setForm({ ...blank, ...item, rounds: item.rounds || [] }); setEdit(false); onChanged?.(); } catch { setError('Could not save the interview.'); } };
  const remove = async () => { if (!chosen || !window.confirm(`Delete ${chosen.companyName}? This also removes its linked application.`)) return; try { await interviewService.delete(chosen.id); close(); await load(); onChanged?.(); } catch { setError('Could not delete the interview.'); } };
  return <Stack spacing={3}>
    <PageHeader title="Interviews" description="Plan upcoming interviews and preparation." actions={<Button variant="contained" startIcon={<AddRounded />} onClick={() => { setChosen(null); setForm(blank); setEdit(true); }}>Schedule interview</Button>} />
    {error && <Alert severity="error">{error}</Alert>}
    <Box sx={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(285px,1fr))', gap: 2 }}>{items.map(item => <SectionCard key={item.id} onClick={() => open(item)} sx={{ cursor: 'pointer' }}><Typography variant="h5">{item.companyName}</Typography><Typography color="text.secondary">{item.role}</Typography><Typography variant="body2" sx={{ mt: 1 }}>{formatPackage(item.packageDetails)} · {item.totalRounds} rounds</Typography><Typography variant="caption" color="text.secondary">{(item.rounds || []).join(' → ')}</Typography></SectionCard>)}</Box>
    <Dialog open={Boolean(chosen) || edit} onClose={close} fullWidth maxWidth="sm"><DialogTitle><Stack direction="row" justifyContent="space-between"><Box><Typography variant="h4">{form.companyName || 'Schedule interview'}</Typography><Typography color="text.secondary">{form.role}</Typography></Box><IconButton onClick={close}><CloseRounded /></IconButton></Stack></DialogTitle><DialogContent dividers>{edit ? <Stack spacing={2}><TextField label="Company" value={form.companyName} onChange={event => setForm({ ...form, companyName: event.target.value })} /><TextField label="Role" value={form.role} onChange={event => setForm({ ...form, role: event.target.value })} /><TextField type="number" inputProps={{ min: 0, step: '0.1' }} label="Package (LPA)" value={form.packageDetails || ''} onChange={event => setForm({ ...form, packageDetails: event.target.value })} helperText="Enter the annual package in LPA, e.g. 12" /><TextField type="date" label="Interview date" InputLabelProps={{ shrink: true }} value={form.interviewDate} onChange={event => setForm({ ...form, interviewDate: event.target.value })} /><TextField type="time" label="Interview time" InputLabelProps={{ shrink: true }} value={form.interviewTime || ''} onChange={event => setForm({ ...form, interviewTime: event.target.value })} /><RoundBuilder totalRounds={form.totalRounds} rounds={form.rounds || []} onChange={(totalRounds, rounds) => setForm({ ...form, totalRounds, rounds })} /><TextField multiline minRows={3} label="Notes" value={form.notes || ''} onChange={event => setForm({ ...form, notes: event.target.value })} /></Stack> : <Stack spacing={2}><Typography>Package: {formatPackage(form.packageDetails)}</Typography><Typography>Estimated monthly: {monthlyEstimate(form.packageDetails)}</Typography><Typography>Scheduled: {form.interviewDate} · {form.interviewTime || 'Time not set'}</Typography><Typography variant="h6">Recruitment process · {form.totalRounds} rounds</Typography>{(form.rounds || []).map((round, index) => <Typography key={index}>{index + 1}. {round}</Typography>)}<Typography color="text.secondary">{form.notes || 'No notes added.'}</Typography></Stack>}</DialogContent><DialogActions>{edit ? <><Button onClick={() => chosen ? (setForm({ ...blank, ...chosen, rounds: chosen.rounds || [] }), setEdit(false)) : close()}>Cancel</Button><Button variant="contained" onClick={save}>Save changes</Button></> : <><Button color="error" startIcon={<DeleteRounded />} onClick={remove} sx={{ mr: 'auto' }}>Delete</Button><Button onClick={close}>Close</Button><Button variant="contained" startIcon={<EditRounded />} onClick={() => setEdit(true)}>Edit</Button></>}</DialogActions></Dialog>
  </Stack>;
}
