import React, { useEffect, useState } from 'react';
import { Alert, Box, Button, CircularProgress, Stack, TextField, Typography } from '@mui/material';
import { DescriptionRounded, OpenInNewRounded, SaveRounded, UploadFileRounded } from '@mui/icons-material';
import { profileService } from '../../services/api';
import PageHeader from '../UI/PageHeader';
import SectionCard from '../UI/SectionCard';

export default function Resume() {
  const [url, setUrl] = useState(''); const [uploaded, setUploaded] = useState(false); const [uploadedName, setUploadedName] = useState(''); const [file, setFile] = useState(null); const [previewUrl, setPreviewUrl] = useState(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const isGoogleDrive = /drive\.google\.com|docs\.google\.com/i.test(url);
  const applyProfile = data => { setUrl(data.resumeUrl || ''); setUploaded(Boolean(data.hasUploadedResume)); setUploadedName(data.uploadedFileName || ''); };
  const loadPreview = async () => { try { const response = await profileService.getUploadedResume(); const objectUrl = URL.createObjectURL(response.data); setPreviewUrl(previous => { if (previous) URL.revokeObjectURL(previous); return objectUrl; }); } catch { setPreviewUrl(''); } };
  useEffect(() => { profileService.getResume().then(response => { const data = response.data; applyProfile(data); if (data.hasUploadedResume) void loadPreview(); }).catch(() => setError('Could not load your resume profile.')).finally(() => setLoading(false)); }, []);
  useEffect(() => () => { if (previewUrl) URL.revokeObjectURL(previewUrl); }, [previewUrl]);
  const saveLink = async () => { setSaving(true); setError(''); try { const response = await profileService.updateResume(url); applyProfile(response.data); } catch { setError('Could not save the resume link.'); } finally { setSaving(false); } };
  const upload = async () => { if (!file) return; if (file.type !== 'application/pdf') { setError('Please select a PDF file.'); return; } setSaving(true); setError(''); try { const response = await profileService.uploadResume(file); applyProfile(response.data); setFile(null); await loadPreview(); } catch { setError('Could not upload the resume.'); } finally { setSaving(false); } };
  return <Stack spacing={3}>
    <PageHeader title="My Resume" description="Upload a PDF from your device or keep a shareable resume link." />
    {error && <Alert severity="error">{error}</Alert>}
    <SectionCard title="Upload from device" subtitle="PDF only, up to 10 MB. Your uploaded resume can be previewed directly here."><Stack spacing={2}><Button component="label" variant="outlined" startIcon={<UploadFileRounded />} sx={{ alignSelf: 'flex-start' }}>Choose PDF<input hidden type="file" accept="application/pdf" onChange={event => setFile(event.target.files?.[0] || null)} /></Button>{file && <Typography variant="body2">Selected: {file.name}</Typography>}<Button variant="contained" disabled={!file || saving} startIcon={<UploadFileRounded />} onClick={upload} sx={{ alignSelf: 'flex-start' }}>{saving ? 'Uploading…' : 'Upload resume'}</Button>{uploaded && <Typography variant="body2" color="text.secondary">Current uploaded file: {uploadedName}</Typography>}</Stack></SectionCard>
    <SectionCard title="Or use a resume link" subtitle="Paste a shareable PDF or Google Drive link."><Stack spacing={2}><TextField fullWidth label="Resume URL" value={url} onChange={event => setUrl(event.target.value)} placeholder="https://drive.google.com/..." /><Stack direction={{ xs: 'column', sm: 'row' }} spacing={1}><Button variant="contained" disabled={saving} startIcon={<SaveRounded />} onClick={saveLink}>{saving ? 'Saving…' : 'Save resume link'}</Button>{url && <Button component="a" href={url} target="_blank" rel="noreferrer" startIcon={<OpenInNewRounded />}>Open link</Button>}</Stack></Stack></SectionCard>
    {loading ? <SectionCard title="Resume preview"><Box sx={{ height: 420, display: 'grid', placeItems: 'center' }}><CircularProgress /></Box></SectionCard> : previewUrl ? <SectionCard title="Resume preview" subtitle={`Uploaded file: ${uploadedName}`}><Box sx={{ width: '100%', maxWidth: 920, mx: 'auto', aspectRatio: '210 / 297', maxHeight: 'calc(100dvh - 220px)', minHeight: { xs: 440, sm: 620 }, bgcolor: 'background.default', border: 1, borderColor: 'divider', borderRadius: 2, overflow: 'hidden' }}><iframe title="Uploaded resume preview" src={previewUrl} style={{ width: '100%', height: '100%', border: 0 }} /></Box></SectionCard> : url && !isGoogleDrive ? <SectionCard title="Resume preview" subtitle="Preview may depend on your link sharing permissions."><Box sx={{ width: '100%', maxWidth: 920, mx: 'auto', aspectRatio: '210 / 297', maxHeight: 'calc(100dvh - 220px)', minHeight: { xs: 440, sm: 620 }, bgcolor: 'background.default', border: 1, borderColor: 'divider', borderRadius: 2, overflow: 'hidden' }}><iframe title="Resume preview" src={url} style={{ width: '100%', height: '100%', border: 0 }} /></Box></SectionCard> : <SectionCard><Stack alignItems="center" spacing={1.5} sx={{ py: 5, textAlign: 'center', maxWidth: 520, mx: 'auto' }}><DescriptionRounded color="primary" sx={{ fontSize: 42 }} /><Typography variant="h5">{isGoogleDrive ? 'Your resume is stored in Google Drive' : 'No resume preview yet'}</Typography><Typography color="text.secondary">{isGoogleDrive ? 'Google Drive links open securely in a new tab. Upload a PDF above if you want to preview it directly in this app.' : 'Upload a PDF from your device or add a shareable resume link.'}</Typography>{url && <Button component="a" href={url} target="_blank" rel="noreferrer" variant="contained" startIcon={<OpenInNewRounded />}>Open resume</Button>}</Stack></SectionCard>}
  </Stack>;
}
