import React,{useState}from'react';
import{Button,Dialog,DialogActions,DialogContent,DialogTitle,FormControl,InputLabel,MenuItem,Select,Stack,TextField}from'@mui/material';
const standard=['OA','Group Discussion','Coding','TR','HR'];
export default function RoundBuilder({totalRounds,rounds=[],onChange,showCurrent=false,currentRoundNumber=1,onCurrentChange}){
 const[prompt,setPrompt]=useState(null),[value,setValue]=useState('');
 const setCount=n=>onChange(n,Array.from({length:n},(_,i)=>rounds[i]||''));
 const confirm=()=>{if(prompt==='count'){setCount(Math.max(5,Number(value)||5));}else if(value.trim()){const next=[...rounds];next[prompt]=value.trim();onChange(totalRounds,next);}setPrompt(null);};
 const changeRound=(index,nextValue)=>{if(nextValue==='CUSTOM'){setPrompt(index);setValue('');return;}const next=[...rounds];next[index]=nextValue;onChange(totalRounds,next);};
 return <Stack spacing={2}>
  <FormControl fullWidth><InputLabel>Total rounds</InputLabel><Select label="Total rounds" value={totalRounds>4?'OTHER':String(totalRounds)} renderValue={selected=>selected==='OTHER'?String(totalRounds):selected} onChange={event=>event.target.value==='OTHER'?(setPrompt('count'),setValue(String(Math.max(5,totalRounds)))):setCount(Number(event.target.value))}>{[1,2,3,4].map(number=><MenuItem key={number} value={String(number)}>{number}</MenuItem>)}<MenuItem value="OTHER">Other (more than 4)</MenuItem></Select></FormControl>
  {rounds.map((round,index)=><FormControl fullWidth key={index}><InputLabel>Round {index+1}</InputLabel><Select label={`Round ${index+1}`} value={round || ''} displayEmpty renderValue={selected=>selected||'Select round type'} onChange={event=>changeRound(index,event.target.value)}><MenuItem value="" disabled><em>Select round type</em></MenuItem>{standard.map(option=><MenuItem key={option} value={option}>{option}</MenuItem>)}<MenuItem value="CUSTOM">+ Add custom round</MenuItem></Select></FormControl>)}
  {showCurrent&&<><FormControl fullWidth><InputLabel>Current round number</InputLabel><Select label="Current round number" value={String(currentRoundNumber)} onChange={event=>onCurrentChange(Number(event.target.value),rounds[Number(event.target.value)-1]||'')}>{Array.from({length:totalRounds},(_,index)=><MenuItem key={index+1} value={String(index+1)}>{index+1}</MenuItem>)}</Select></FormControl><TextField label="Current round" value={rounds[currentRoundNumber-1]||'Not selected'} InputProps={{readOnly:true}} helperText="Set automatically from the selected round order." /></>}
  <Dialog open={prompt!==null} onClose={()=>setPrompt(null)} fullWidth maxWidth="xs"><DialogTitle>{prompt==='count'?'How many rounds?':'Add custom round'}</DialogTitle><DialogContent><TextField autoFocus fullWidth sx={{mt:1}} type={prompt==='count'?'number':'text'} label={prompt==='count'?'Total (minimum 5)':'Round name'} value={value} onChange={event=>setValue(event.target.value)}/></DialogContent><DialogActions><Button onClick={()=>setPrompt(null)}>Cancel</Button><Button variant="contained" onClick={confirm}>Add</Button></DialogActions></Dialog>
 </Stack>;
}
